<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions name="billing"
	targetNamespace="http://www.example.org/billing"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://www.example.org/billing" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<wsdl:message name="createBilling">
		<wsdl:part name="rentalPrice" type="xsd:double"/>
		<wsdl:part name="rentalDays" type="xsd:integer"/>
		<wsdl:part name="deliveryPrice" type="xsd:double"/>
		<wsdl:part name="bankAccount" type="xsd:string"/>
	</wsdl:message>
	<wsdl:message name="createBillingResponse">
		<wsdl:part name="succeeded" type="xsd:boolean"/>
	</wsdl:message>
	
	<wsdl:portType name="billingPortType">
		<wsdl:operation name="billing">
			<wsdl:input message="tns:createBilling"/>
			<wsdl:output message="tns:createBillingResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="billingBinding" type="tns:billingPortType">
		<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="billing">
			<soap:operation style="rpc"/>
			<wsdl:input>
				<soap:body use="literal" namespace="http://www.example.org/billing"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" namespace="http://www.example.org/billing"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="billingService">
		<wsdl:port name="billingPort" binding="tns:billingBinding">
			<soap:address location="http://localhost:8080/SOA-project/services/billingService"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>