<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="delivery" targetNamespace="http://www.example.org/delivery" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.example.org/delivery" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:customer="http://www.example.org/customer">
  <wsdl:types>
    <xsd:schema>
	      <xsd:import id="customer.xsd" namespace="http://www.example.org/customer" schemaLocation="customer.xsd"/>
	    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="requestDelivery">
    <wsdl:part name="weight" type="xsd:string">
    </wsdl:part>
    <wsdl:part name="iceSkatesID" type="xsd:integer">
    </wsdl:part>
    <wsdl:part name="customer" type="customer:Customer">
    </wsdl:part>
    <wsdl:part name="callbackURL" type="xsd:string">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="deliveryPortType">
    <wsdl:operation name="delivery">
      <wsdl:input message="tns:requestDelivery">
    </wsdl:input>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="deliveryBinding" type="tns:deliveryPortType">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="delivery">
      <soap:operation style="rpc"/>
      <wsdl:input>
        <soap:body use="literal" namespace="http://www.example.org/delivery"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="deliveryService">
    <wsdl:port name="deliveryPort" binding="tns:deliveryBinding">
      <soap:address location="http://localhost:8080/SOA-project/services/deliveryService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
